import = [
    "~/.config/alacritty/themes/themes/{theme}.toml"
]

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
decorations = "Full"
padding = { x = 10, y = 10 }

[font]
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
size = 16
offset = { x = 0, y = 10 }
glyph_offset = { x = 0, y = 5 }
